environment: "Development"

api:
  port: 5000
  connectionString: "sqlserver://sa:@stefany@1994@localhost:1433?database=ChallengeAppointments"
  examsBaseUrl: "http://www.mocky.io/v2/5d681ede33000054e7e65c3f"

notifier:
  serviceBus:
    connectionString: ""
    queueName: ""
