environment: "Development"

api:
  port: 3000
  connectionString: "sqlserver://sa:@stefany@1994@localhost:1433?database=ChallengeAppointments"

notifier:
  serviceBus:
    connectionString: ""
    queueName: ""
